### ISSUE TITLE
compile fails on Slack 14.1

### ISSUE THREAD

**Issue by broken-saber** [ryanpcmcquen/slackENLIGHTENMENT#1]
Compile fails with the below error copied and pasted from my terminal.  Hope this help, I'd like to get E19 running on my box.  I'm compiling on a fresh & updated (via slackpkg) Slack 14.1 install.

checking whether to enable TGV image loader... static
checking whether TGV image loader will be built... yes
checking whether to enable DDS image loader... static
checking whether DDS image loader will be built... yes
checking for EVAS... yes
checking hb-ft.h usability... no
checking hb-ft.h presence... no
checking for hb-ft.h... no
configure: error: Harfbuzz-ft (hb-ft.h) not found
bash-4.2#

**Comment by ryanpcmcquen** [comment]
Sorry you are having issues!

Did you uncomment [these lines](https://github.com/ryanpcmcquen/slackENLIGHTENMENT#on-stable-remember-to-uncomment-these-lines)?

Also, are you running a full install?

**Comment by ryanpcmcquen** [comment]
@broken-saber since I haven't heard back from you and I can compile this on a full 14.1 install, I am closing this. Make sure you have _harfbuzz_ installed (it is included with a full Slackware install).
