### ISSUE TITLE
Don't try to reinstall dependencies if they are already met

### ISSUE THREAD

**Issue by denydias** [ryanpcmcquen/slackENLIGHTENMENT#13]
@ryanpcmcquen, first and foremost, thank you for these beautiful scripts. As you've said, 'Enlightenment for Slackware! What could go wrong?'.

I want to propose the following patch:

```patch
diff --git a/enlighten-me.sh b/enlighten-me.sh
index 04df539..530d726 100755
--- a/enlighten-me.sh
+++ b/enlighten-me.sh
@@ -23,7 +23,7 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 # This is where all the compilation and final results will be placed
-TMP=${TMP:-/tmp}
+TMP=/tmp
 
 # This is the original directory where you started this script
 ROOT=$(pwd)
@@ -37,11 +37,19 @@ sbo_pkg_install() {
 }
 
 sbopkg -r
-## grab these from SBo
-sbo_pkg_install lua
-sbo_pkg_install luajit
-sbo_pkg_install bullet
-sbo_pkg_install libwebp
+## grab these from SBo if they aren't already installed
+if [ ! -x /usr/bin/lua ]; then
+  sbo_pkg_install lua
+fi
+if [ ! -L /usr/bin/luajit ]; then
+  sbo_pkg_install luajit
+fi
+if [ ! -L /usr/lib64/libBulletDynamics.so ]; then
+  sbo_pkg_install bullet
+fi
+if [ ! -L /usr/lib64/libwebp.so ]; then
+  sbo_pkg_install libwebp
+fi
```

In fact, this is a two-in-one patch.

1. Force tmp directory to be '/tmp' as it looks more reliable for the ones using '/dev/shm' as tmp, which avoids `Error:  package to upgrade "$PACKAGE" not found in $TMP`.

2. As the title says, first check if dependencies are properly installed before trying to install them, hence making upgrades a lot faster. The check itself is not the most robust one, but it should works in most circumstances to verify if those dependencies are already met. Feel free to improve it.

**Comment by ryanpcmcquen** [comment]
The function already checks for dependencies:
https://github.com/ryanpcmcquen/slackENLIGHTENMENT/blob/master/enlighten-me.sh#L31-L37

No reinstall happens if they already exist.

**Comment by denydias** [comment]
Indeed! I haven't read the code properly as I was just concerned on skip already installed stuff.

The other patch still applies though.

**Comment by ryanpcmcquen** [comment]
No thanks on the other patch, if the user wants to set `TMP` to something nonsensical, that is their prerogative.
