### ISSUE TITLE
not all dependencies handled.

### ISSUE THREAD

**Issue by kevison** [ryanpcmcquen/slackENLIGHTENMENT#15]
LUA and BULLET were not handled by the script.  I had to manually install these and then re-run the build script.

**Comment by ryanpcmcquen** [comment]
Do you have `sbopkg` installed?

**Comment by kevison** [comment]
Yes I do.

**Comment by ryanpcmcquen** [comment]
What was the output for the `lua` and `bullet` build that failed?

**Comment by kevison** [comment]
That it needed lua 5.1 or 5.2 and then it said it needed bullet >= 2.8.

**Comment by ryanpcmcquen** [comment]
What was the output from those respective builds though (`lua` and `bullet`) while running `enlighten-me.sh`?

**Comment by kevison** [comment]
where would the log be that would have that info?

**Comment by ryanpcmcquen** [comment]
If you still have the terminal window open, you could scroll back to it. Otherwise, check `/var/log/sbopkg`.

**Comment by kevison** [comment]
I dont have the terminal open... I had shutdown the vm, before taking off to a meeting... there is nothing in the /var/log/sbopkg folder.   I also just ran "sbopkg -r" to make sure there was nothing wrong with the sbopkg installation and its complaining about being able to get to slackbuilds.org... that may have been part of the problem....

**Comment by ryanpcmcquen** [comment]
That would do it. If the network is wonky or `sbopkg.org` is down the script won't account for that.

**Comment by ryanpcmcquen** [comment]
Thanks for reporting but this sounds like a larger system issue, I do not plan to accomodate that in the `enlighten-me.sh` script, doing so would add needless complexity.

**Comment by kevison** [comment]
ok.
