### ISSUE TITLE
Nice work, but compiled without pam support, so no password prompt on screenlock

### ISSUE THREAD

**Issue by jlive80** [ryanpcmcquen/slackENLIGHTENMENT#16]
Nice work, but compiled without pam support, so no password prompt on screenlock

Good day,
Andreas

**Comment by pyllyukko** [comment]
You can use [XScreenSaver](https://www.jwz.org/xscreensaver/) for screen locking.

**Comment by ryanpcmcquen** [comment]
Slackware doesn't have Pam ...
