### ISSUE TITLE
Crashes after latest current (64) updates (Oct 19  2018)

### ISSUE THREAD

**Issue by jnontour** [ryanpcmcquen/slackENLIGHTENMENT#19]
Hello,

After updating slackware64-current, enlightenment crashes. Erased packages and compiled again but error persisted.

Crashdump only says:

"The program is not being run."

Image of the error:
![image](https://user-images.githubusercontent.com/44325561/47259469-77baf680-d46f-11e8-812d-dc12fdb6e7cb.png)

**Comment by ryanpcmcquen** [comment]
You said you have a fix for this? Would you mind putting in a pull request? @matsbtegner should also be able to help, he is an Enlightenment expert.

**Comment by matsbtegner** [comment]
This has happened to me as well. I would suggest using the SlackBuild-scripts from SlackBuilds.org as a workaround.

**Comment by ryanpcmcquen** [comment]
First thing to try is to change the versions to those used on SBo.

**Comment by ryanpcmcquen** [comment]
Closing due to age, please reopen if this is still valid.
