### ISSUE TITLE
python-efl doesn't build

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [ryanpcmcquen/slackENLIGHTENMENT#22]
it ends here:

building 'efl.elementary.__init__' extension
creating build/temp.linux-x86_64-2.7/efl/elementary
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 -Iinclude/ -I/usr/include/python2.7 -c efl/elementary/__init__.c -o build/temp.linux-x86_64-2.7/efl/elementary/__init__.o -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-evas-1 -I/usr/include/libmount -I/usr/include/glib-2.0 -I/usr/include/efl-1/interfaces -D_REENTRANT -I/usr/include/blkid -I/usr/include/ecore-input-1 -I/usr/include/emile-1 -I/usr/include/harfbuzz -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/efl-1 -I/usr/include/edje-1 -I/usr/include/eeze-1 -I/usr/include/efreet-1 -I/usr/include/eina-1/eina -I/usr/include/ecore-con-1 -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-file-1 -I/usr/include/eet-1 -I/usr/include/emotion-1 -I/usr/include/evas-1/canvas -I/usr/include/ethumb-1 -I/usr/include/eldbus-1 -I/usr/lib64/dbus-1.0/include -I/usr/include/ecore-imf-1 -I/usr/include/libpng16 -I/usr/include/embryo-1 -I/usr/include/evas-1 -I/usr/include/ector-1 -I/usr/include/ethumb-client-1 -I/usr/include/ecore-audio-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-x-1 -pthread -I/usr/include/ecore-1 -I/usr/include/libxml2 -I/usr/include/ecore-drm2-1 -I/usr/include/eio-1 -I/usr/include/eina-1 -I/usr/include/luajit-2.0 -I/usr/include/dbus-1.0 -I/usr/include/elementary-1 -I/usr/include/freetype2 -I/usr/include/eo-1 -I/usr/include/evas-1/gesture -fno-var-tracking-assignments -Wno-misleading-indentation -Wno-deprecated-declarations -Wno-unused-variable -Wno-format-security
gcc: fatal error: Killed signal terminated program cc1
compilation terminated

**Comment by matsbtegner** [comment]
I cannot reproduce this on my system. Builds fine against EFL 1.24.3
https://github.com/matsbtegner/slackENLIGHTENMENT/blob/master/python-efl/python-efl.SlackBuild

**Comment by sashaaaaaaaaa** [comment]
Well I tried it on my host system and not in a VM and it worked there, so maybe there was just something messed up about my VM.
