### ISSUE TITLE
Errors building efl on fresh 15.0 (scim, ibus)

### ISSUE THREAD

**Issue by fgerent** [ryanpcmcquen/slackENLIGHTENMENT#23]
Hi,
I was trying to build the packages on a fresh Slackware 15.0 (full install) and got a couple of errors while trying to build efl (at the meson build step)
- scim was missing
- glib needs to be enabled if ibus is used (I think this only popped up once I tried to fix the first error)

I figured I don't need either of these, so I added the following to my slackbuild script:
-Decore-imf-loaders-disabler=scim,ibus \
which seems to have fixed the issue for me.

Hopefully this can help others who run into the same issue, not sure if there's a way to incorporate this into the Slackbuild script while still leaving the option for anyone who actually needs scim?

**Comment by ryanpcmcquen** [comment]
@matsbtegner do you have any tips here?

**Comment by ryanpcmcquen** [comment]
`ibus` is included in Slackware, what features does `scim` add?

**Comment by matsbtegner** [comment]
@ryanpcmcquen no unfortunately not. I haven't installed 15.0 yet

**Comment by ryanpcmcquen** [comment]
I'll try to spin up a VM and poke around.

**Comment by fgerent** [comment]
I have some updates on this.

I was able to build, install and run everything using both options mentioned above. (1) disabling both scim and ibus, or (2) disabling scim and enabling glib for ibus use:
-Decore-imf-loaders-disable=scim \
-Dglib=true \

I think option 2 (using ibus) might be better as a default for slackware, but I'm not really familiar with what scim/ibus are supposed to provide and I suspect that my use case (US keyboard, ENG-US) wouldn't use either much anyway.

On a mostly unrelated note, I ran into issues getting some enlightenment modules loaded and added, but when I tried just building the latest versions of everything (EFL 1.26.2, enlightenment 0.25.2) using the same slackbuild scripts I was able to build and install everything with no further changes, and now everything (including all the modules) works. The only exception was ephoto, which I think just needs to be updated for a meson/ninja build.

**Comment by Sanvido** [comment]
I managed to compile ephoto 1.6.0:

meson ... \
  --buildtype=release
  --infodir=/usr/info
  --libdir=/usr/lib${LIBDIRSUFFIX}
  --libexecdir=/usr/libexec
  --localstatedir=/var
  --mandir=/usr/man
  --prefix=/usr
  --sysconfdir=/etc
  ninja
  DESTDIR=$PKG ninja install
cd ...

I hope it helps

**Comment by ryanpcmcquen** [comment]
@fgerent would you mind pushing up a PR with your changes? I have some testing going here locally, but even with your compile flags I am still getting a scim error.

**Comment by ryanpcmcquen** [comment]
I'm making good progress here, I put together a SlackBuild for `scim` that could probably land on SBo at some point. I'm doing final testing, but hopefully I'll have updates to all the latest versions here over the weekend.

**Comment by ryanpcmcquen** [comment]
@fgerent @Chapinha @matsbtegner
Thanks for your help, check this out:
https://github.com/ryanpcmcquen/slackENLIGHTENMENT/releases/tag/20220213

**Comment by Sanvido** [comment]
@ryanpcmcquen 
Everything works perfectly. Thanks for the great job! :)

**Comment by ryanpcmcquen** [comment]
Thank you for being patient!
